<!DOCTYPE html>
<!--
 * OpenBoleto - Geração de boletos bancários em PHP
 *
 * LICENSE: The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies
 * or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title><?php echo $cedente; ?></title>
    <style type="text/css">
        /* Embed the CSS content here */
        <?php include $resource_path . '/css/styles.css' ?>
    </style>
</head>
<body>

    <div style="width: 666px">
        <div class="noprint info">
            <h3>Instruções de Impressão e pagamento deste bloqueto:</h3>
            <ul>
                <li>Utilize uma impressora tipo jato de tinta (ink jet) ou laser.</li>
                <li>Configure a impressora para utilizar qualidade de impressão Normal. Não utilize as opções Rascunho ou Econômico.</li>
                <li>Imprimir em folha A4 (210 x 297 mm) ou Carta (216 x 279 mm) e margens mínimas à esquerda e à direita do formulário.</li>
                <li>Corte nas linhas indicadas. Não fure, dobre, amasse, rasure ou risque a região onde se encontra o código de barras.</li>
                <li>Caso não apareça o código de barras no final, pressione F5 para atualizar esta tela.</li>
                <li>Caso tenha problemas ao imprimir, copie a sequencia numérica abaixo e pague no caixa eletrônico ou no internet banking:</li>
            </ul>
            <span class="header">Linha Digitável: <?php echo $linha_digitavel; ?></span>
            <?php if ($valor_documento) : ?><span class="header">Valor: R$ <?php echo $valor_documento; ?></span><?php endif ?>
            <br>
            <div class="linha-pontilhada" style="margin-bottom: 20px;">Recibo do sacado</div>
        </div>

	<table class="table-logo" cellpadding="0" cellspacing="0" border="0" style="padding-bottom: 5px;">
            <tr>
                <td valign="bottom" width="100%">
                    <?php
                    if (!empty($logotipo)):
                        $image = getimagesize($logotipo);
                        if ($image[0] > 175 && $image[1] > 75) :
                            echo '<img src="'. $logotipo .'" width="175" height="75">';
                        else :
                            echo '<img src="'. $logotipo .'">';
                        endif;
                     else :
                        echo '<img src="'. $logo_banco .'">';
                     endif;
                    ?>
				</td>
				<td valign="bottom">
                    <table class="mini-table" cellpadding="0" cellspacing="0" border="0">
                        <tr>
                            <td colspan="2" class="recibo-sacado">
                                <p>RECIBO DO SACADO</p>
                            </td>
                        </tr>
                        <tr>
                            <td width="130" class="top-value">
                                Valor
                            </td>
                            <td width="130" class="top-due-date">
                                Vencimento
                            </td>
                         </tr>
                         <tr>
                             <td width="130" class="bottom-value">
                                 <?php echo $valor_documento; ?>
                             </td>
                             <td width="150" class="bottom-due-date">
                                 <?php echo $data_vencimento; ?>
                             <td>
                         </tr>
                    </table>
                </td>
            </tr>
        </table>

        <table class="table-boleto recibo-boleto" cellpadding="0" cellspacing="0" border="0">
            <tbody>
            <tr>
                <td width="180">
                    <div class="titulo title-featured">Agência/Código do Cedente</div>
                    <table width="180" border="0"><tr><td class="conteudo" style="border:none;"><?php echo $agencia_codigo_cedente ?></td></tr></table>
                </td>
                <td width="150">
                   <div class="titulo title-featured">Nosso Número</div>
                   <table width="150" border="0"><tr><td class="conteudo" style="border:none;"><?php echo $nosso_numero ?></td></tr></table>
                </td>
                <td>
                   <div width="150" class="titulo title-featured">Número do Documento</div>
                   <table width="150" border="0"><tr><td class="conteudo" style="border:none;"><?php echo $numero_documento ?></td></tr></table>
                </td>
                <td width="150" class="last-child">
                    <div class="titulo title-featured">Data do documento</div>
		    		<table width="150" border="0"><tr><td class="conteudo" style="border:none;"><?php echo $data_documento ?></td></tr></table>
                </td>
            </tr>
            <tr>
                <td colspan="4" class="last-child final-field">
                    <div class="titulo title-featured">Sacado</div>
                    <div class="conteudo rtl"><?php echo $sacado ?></div>
                </td>
            </tr>
            <tr>
                <td colspan="4" class="last-child final-field" style="border-bottom: 1px solid #000000;">
                    <div class="titulo title-featured">Demonstrativo</div>
                    <div class="conteudo rtl"><?php echo $demonstrativo[0]; ?>
                </td>
            </tr>
            <tr>
                <td colspan="4" style="border: none;text-align:right;">
                    AUTENTICAÇÃO MECÂNICA
                </td>
            </tr>
            </tbody>
        </table>
        <br>
        <div class="linha-pontilhada">&nbsp;</div>

        <!-- Ficha de compensação -->
        <?php include('partials/ficha-de-compensacao.phtml') ?>
    </div>
</body>
</html>
