<!--
 * OpenBoleto - Geração de boletos bancários em PHP
 *
 * LICENSE: The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies
 * or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->

<table class="table-boleto" cellpadding="0" cellspacing="0" border="0" style="font-family:Arial !important;font-size:12px;">
    <tbody>
    <tr>
		<td valign="bottom" colspan="8" class="nopadding last-child" style="border:none;">
			<table cellpadding="0" cellspacing="0" border="0">
				<thead>
					<tr>
						<th class="logobanco">
							<img src="<?php echo $logo_banco; ?>" alt="logotipo do banco">
						</th>
						<th class="codbanco">
							 <div class="codbanco"><?php echo $codigo_banco_com_dv ?></div>
						</th>
						<th width="100%">
							<div class="linha-digitavel"><?php echo $linha_digitavel ?></div>
						</th>
					</tr>
				</thead>
			</table>
        </td>
    </tr>
    <tr>
        <td colspan="7" width="450">
            <div class="titulo">Local de Pagamento</div>
            <div class="conteudo"><?php echo $local_pagamento ?></div>
            <div class="conteudo"></div>
        </td>
        <td width="180" class="last-child">
            <div class="titulo">Vencimento</div>
	   		<table width="180" border="0"><tr><td class="featured" style="text-align:right;border:none;"><?php echo $data_vencimento ?></td></tr></table>
        </td>
    </tr>
    <tr>
        <td colspan="7">
            <div class="titulo">Cedente</div>
            <div class="conteudo"><?php echo $cedente ?></div>
        </td>
        <td width="180" class="last-child">
            <div class="titulo">Agência/Código cedente</div>
	   		<table width="180" border="0"><tr><td style="text-align:right;border:none;"><?php echo $agencia_codigo_cedente ?></td></tr></table>
        </td>
    </tr>
    <tr>
        <td width="150" colspan="2">
            <div class="titulo">Data do documento</div>
            <table width="150" border="0"><tr><td class="conteudo" style="border:none;"><?php echo $data_documento ?></td></tr></table>
        </td>
        <td width="150" colspan="2">
            <div class="titulo">Nº documento</div>
            <table width="150" border="0"><tr><td class="conteudo" style="border:none;"><?php echo $numero_documento ?></td></tr></table>
        </td>
        <td width="80">
            <div class="titulo">Espécie doc.</div>
	    	<table width="80" border="0"><tr><td class="conteudo" style="border:none;"><?php echo $especie_doc ?></td></tr></table>
        </td>
        <td width="70">
            <div class="titulo">Aceite</div>
	    	<table width="60" border="0"><tr><td class="conteudo" style="border:none;"><?php echo $aceite ?></td></tr></table>
            <div class="conteudo"><?php echo $aceite ?></div>
        </td>
        <td width="130">
            <div class="titulo">Data processamento</div>
            <table width="130" border="0"><tr><td class="conteudo" style="border:none;"><?php echo $data_processamento ?></td></tr></table>
        </td>
        <td width="150" class="last-child">
            <div class="titulo">Nosso número</div>
	    	<table width="150" border="0"><tr><td style="text-align:right;border:none;"><?php echo $nosso_numero ?></td></tr></table>
        </td>
    </tr>
    <tr>
	<!-- Não foi retirado esse trexo de código, tão pouco testado -->
        <?php if (!$esconde_uso_banco) : ?>
            <td<?php if (!$mostra_cip) : ?> colspan="2"<?php endif ?>>
                <div class="titulo">Uso do banco</div>
                <div class="conteudo"><?php echo $uso_banco ?></div>
            </td>
        <?php endif; ?>

        <?php if ($mostra_cip) : ?>
            <!-- Campo exclusivo do Bradesco -->
            <td width="20">
                <div class="titulo">CIP</div>
                <div class="conteudo"><?php echo $cip ?></div>
            </td>
        <?php endif ?>
        <!--<td <?php //if($esconde_uso_banco) : ?> colspan="3" <?php //endif; ?>>-->

        <td colspan="2">
	    <div class="titulo">Uso do Banco</div>
	</td>
        <td width="75">
            <div class="titulo">Carteira</div>
            <table width="75" border="0"><tr><td class="conteudo" style="border:none;"><?php echo $carteira ?></td></tr></table>
        </td>
        <td width="75">
            <div class="titulo">Espécie</div>
	    	<table width="75" border="0"><tr><td class="conteudo" style="border:none;"><?php echo $especie ?></td></tr></table>
        </td>
        <td width="120" colspan="2">
            <div class="titulo">Quantidade</div>
            <table width="120" border="0"><tr><td class="conteudo" style="border:none;"><?php echo $quantidade ?></td></tr></table>
        </td>
        <td width="90">
            <div class="titulo">(X) Valor</div>
	    	<table width="90" border="0"><tr><td class="conteudo" style="border:none;"><?php echo $valor_unitario ?></td></tr></table>
        </td>
        <td width="180" class="last-child final-field">
            <div class="titulo">(=) Valor do Documento</div>
	    	<table width="180" border="0"><tr><td class="featured" style="text-align:right;border:none;"><?php echo $valor_documento ?></td></tr></table>
        </td>
    </tr>
    <tr>
        <td colspan="7">
            <div class="titulo">Instruções (Todas as informações deste bloqueto são de exclusiva responsabilidade do cedente)</div>
        </td>
        <td width="180" class="last-child final-field">
            <div class="titulo">(-) Descontos / Abatimentos</div>
	    	<table width="180" border="0"><tr><td style="text-align:right;border:none;"><?php echo $desconto_abatimento ?></td></tr></table>
        </td>
    </tr>
    <tr>
        <td colspan="7" style="border-top:none;">
            <div class="conteudo"><?php echo $instrucoes[0]; ?></div>
            <div class="conteudo"><?php echo $instrucoes[1]; ?></div>
        </td>
        <td width="180" class="last-child final-field">
            <div class="titulo">(-) Outras deduções</div>
	   		<table width="180" border="0"><tr><td style="text-align:right;border:none;"><?php echo $outras_deducoes ?></td></tr></table>
        </td>
    </tr>
    <tr>
        <td colspan="7" class="notopborder" style="border-top:none;">
            <div class="conteudo"><?php echo $instrucoes[2]; ?></div>
            <div class="conteudo"><?php echo $instrucoes[3]; ?></div>
        </td>
        <td width="180" class="last-child final-field">
            <div class="titulo">(+) Mora / Multa</div>
	    	<table width="180" border="0"><tr><td style="text-align:right;border:none;"><?php echo $mora_multa ?></td></tr></table>
        </td>
    </tr>
    <tr>
        <td colspan="7" style="border-top:none;">
            <div class="conteudo"><?php echo $instrucoes[4]; ?></div>
            <div class="conteudo"><?php echo $instrucoes[5]; ?></div>
        </td>
        <td width="180" class="last-child final-field">
            <div class="titulo">(+) Outros acréscimos</div>
	    	<table width="180" border="0"><tr><td style="text-align:right;border:none;"><?php echo $outros_acrescimos ?></td></tr></table>
        </td>
    </tr>
    <tr>
        <td colspan="7" style="border-top:none;">
            <div class="conteudo"><?php echo $instrucoes[6]; ?></div>
            <div class="conteudo"><?php echo $instrucoes[7]; ?></div>
        </td>
        <td width="180" class="last-child final-field">
            <div class="titulo">(=) Valor cobrado</div>
	    	<table width="180" border="0"><tr><td style="text-align:right;border:none;"><?php echo $valor_cobrado ?></td></tr></table>
        </td>
    </tr>
    <tr>
        <td colspan="7" class="final-field" style="border-bottom: 1px solid #000000;">
            <div class="titulo">SACADO AVALISTA:</div>
            <div class="conteudo"><?php echo $sacado ?></div>
            <div class="conteudo"><?php echo $sacado_endereco1 ?></div>
            <div class="conteudo"><?php echo $sacado_endereco2 ?></div>

        </td>
        <td class="last-child" style="border-bottom: 1px solid #000000; border-left:none;">
            <div class="titulo" style="margin-top: 50px">CNPJ/CPF:</div>
        </td>
    </tr>
    <tr>
        <td colspan="8" class="last-child" style="border:none;text-align:right;">
            <div class="conteudo rtl">Ficha de Compensação / Autenticação mecânica</div>
        </td>
    </tr>
    <tr>
	<td colspan="8" class="last-child" style="border:none;">
 	    <?php echo $codigo_barras; ?>
	</td>
    </tr>
    </tbody>
</table>
<div class="linha-pontilhada">&nbsp;</div>
